# Tasks that can be completed by the Agent
tasks_agent_can_complete = [
    "Analyze Tesla's Q1 2024 financial report and extract key financial metrics.",
    "Retrieve Apple's annual reports from the past 10 years from the database and calculate its revenue growth rate.",
    "Compare the subscription user growth trends of Netflix and Disney+ and visualize the results.",
    "Search Starbucks' expansion strategy in China and summarize its main measures.",
    "Based on Amazon AWS's revenue data from the past 5 years, forecast its growth for 2026.",
    "Analyze SpaceX's latest funding round and summarize the list of investment institutions.",
    "Evaluate Google's market share in generative AI and compare it with OpenAI.",
    "Calculate the market share of Microsoft Azure and Google Cloud in the IaaS sector.",
    "Search for the most popular series on Netflix globally and analyze their rating data.",
    "Analyze Shopify's competitiveness in the e-commerce SaaS sector and forecast future growth.",
    "Retrieve e-commerce revenue data from Walmart and Amazon from the database and perform a comparative analysis.",
    "Calculate the market share of Apple's iPhone in North America and forecast trends for 2025.",
    "Retrieve Zoom's financial reports from the past 3 years and analyze its profitability.",
    "Extract Airbnb's primary revenue models from business documents and visualize the results.",
    "Search Nvidia's GPU market share and analyze AMD's competitive position.",
    "Based on Netflix's subscription data, forecast its user growth in the Indian market.",
    "Calculate the store growth rates of McDonald's and KFC in the global market and analyze their competitive position.",
    "Retrieve Facebook (Meta)'s advertising revenue data and compare it with TikTok.",
    "Analyze PayPal's penetration in the global payment market and compare it with Stripe.",
    "Search for Boeing and Airbus's order data and forecast the market demand for the next 5 years.",
    "Calculate the profit margin of Samsung and Apple in the smartphone market and analyze its trend.",
    "Analyze the growth of BYD and Tesla in the electric vehicle market and visualize the data.",
    "Retrieve Google's search ad and YouTube ad revenue share and analyze its trends.",
    "Calculate Huawei's global market share in the 5G equipment market and analyze future trends.",
    "Analyze TikTok's revenue in the U.S. market and forecast its growth rate for 2025.",
    "Calculate the sales of Nike and Adidas in the sports shoe market and compare their growth rates.",
    "Retrieve funding data for OpenAI and Anthropic and compare their funding sources.",
    "Search for Pinduoduo's GMV (Gross Merchandise Value) and forecast its growth for 2025.",
    "Analyze Qualcomm's competitiveness in the 5G chip market and compare it with MediaTek's data.",
    "Calculate Spotify's market share in the music streaming market and forecast future growth trends.",
    "Analyze ByteDance's advertising revenue globally and compare it with Meta.",
    "Calculate Netflix's subscription growth rate in the Latin American market and visualize the data.",
    "Search for Reddit's recent funding situation and summarize the list of investment institutions.",
    "Analyze Tesla's investment in autonomous driving and compare it with Waymo.",
    "Calculate YouTube's ad revenue in the short video market and compare it with TikTok.",
    "Retrieve Alibaba's GMV data in the Southeast Asian market and analyze its growth trend.",
    "Search Xiaomi's smartphone sales in the European market and forecast its performance for 2025.",
    "Analyze Intel's market share in the AI chip sector and compare it with AMD and Nvidia.",
    "Calculate Airbnb's active listings in the North American market and forecast future growth.",
    "Analyze Apple's Vision Pro's sales and forecast future market trends.",
    "Search ByteDance's international advertising business growth and compare it with Meta.",
    "Retrieve Walmart and Amazon's e-commerce market share and analyze the competitive position.",
    "Calculate Adobe's annual growth rate in SaaS subscription services and forecast future trends.",
    "Analyze the market demand for Tesla's Cybertruck and forecast sales data.",
    "Search OpenAI's API revenue growth and compare it with Anthropic.",
    "Calculate Lululemon's growth rate in the sports apparel market and analyze its competitive position.",
    "Retrieve Zoom's market share in the enterprise communication market and forecast its growth.",
    "Analyze TikTok's live-streaming e-commerce GMV data and forecast future trends.",
    "Calculate Twitter's (X) ad revenue for 2024 and forecast its performance.",
    "Search OpenAI's growth in the enterprise SaaS sector and compare it with Google DeepMind."
]

# Tasks that the Agent cannot complete (due to insufficient tools)
tasks_agent_cannot_complete = [
    "Generate a report for Tesla based on database data and online data and upload it to the database.",
    "Identify the top 5 companies in the electric vehicle industry and download their reports locally.",
    "Retrieve Amazon's financial reports from the past 10 years and organize them into an Excel file for download.",
    "Extract Apple's financial data from the database and automatically generate a PowerPoint presentation.",
    "Compare Netflix and Disney+'s user growth data and generate an interactive BI dashboard.",
    "Retrieve SpaceX's financing data from the past 5 years and store it as JSON for API use.",
    "Retrieve Microsoft Azure and Google Cloud's revenue data from the database and generate a Markdown report.",
    "Analyze BYD and Tesla's market share changes and automatically send a report via email.",
    "Convert Pinduoduo's GMV data into a CSV file and upload it to cloud storage.",
    "Calculate Facebook and TikTok's ad market share globally and automatically generate dynamic charts.",
    "Retrieve Walmart and Amazon's e-commerce sales data and store it in the database for future querying.",
    "Analyze the market demand for Tesla's Cybertruck and generate an automated summary for API queries.",
    "Calculate Apple's smartphone sales share in North America and export the report in PDF format.",
    "Forecast Airbnb's user growth over the next 3 years and generate a dynamic visualization webpage.",
    "Calculate Adobe's growth rate in the SaaS sector and store it in the database for BI tool use.",
    "Analyze Shopify's competitiveness in the market and synchronize the results to the CRM system.",
    "Retrieve OpenAI and Anthropic's funding data and automatically generate a comparative analysis PDF.",
    "Calculate ByteDance and Meta's global ad revenue and generate an Excel visualization table.",
    "Retrieve Netflix's subscription data in the Asian market and generate an API for use.",
    "Retrieve Samsung and Apple's profit margins in the smartphone market and export the data as JSON.",
    "Compare Zoom and Google Meet's enterprise user growth data and generate an automated summary report.",
    "Analyze PayPal and Stripe's competition in the payment market and generate a Markdown memo.",
    "Calculate TikTok live-streaming e-commerce GMV data and automatically store it in the BI platform.",
    "Forecast Starbucks' expansion speed in China and generate a dynamic report in HTML format.",
    "Retrieve Boeing and Airbus's order data and generate a CSV file for download.",
    "Extract Qualcomm and MediaTek's market share data from the database and automatically generate a dynamic dashboard.",
    "Retrieve Lululemon and Nike's sales data and synchronize it to Google Sheets.",
    "Calculate Airbnb's listing growth in the European market and generate an API for developers to query.",
    "Retrieve Twitter's (X) 2024 ad revenue and generate a PDF report.",
    "Compare OpenAI and Google DeepMind's SaaS business growth and output JSON structured data.",
    "Analyze Walmart and Amazon's e-commerce competition in the North American market and generate a Markdown memo.",
    "Calculate Tesla's patent growth trends in the autonomous driving market and automatically generate visual charts.",
    "Forecast Nvidia's market share in AI computing and export the data in CSV format.",
    "Retrieve Xiaomi's smartphone sales data in the European market and store it in the database for analysis.",
    "Calculate Reddit's user growth over the past 5 years and generate an Excel table.",
    "Compare Airbnb and Booking.com's global market share and generate a visual analysis PDF.",
    "Retrieve Facebook and Instagram's ad market growth data and export it as JSON.",
    "Calculate Tesla's electric vehicle sales over the next 3 years and generate an API for use by other systems.",
    "Analyze YouTube and TikTok's ad revenue in the short video market and automatically generate a summary report.",
    "Calculate Shopify's market penetration in independent site e-commerce and export the data in Excel for BI analysis.",
    "Retrieve ByteDance's global ad market growth data and generate a Markdown report.",
    "Compare Google Cloud and AWS's revenue data and automatically generate a comparative HTML report.",
    "Calculate Netflix's subscription churn rate in the North American market and export the data as CSV.",
    "Forecast Alibaba's GMV growth in Southeast Asia and generate a dynamic visualization report.",
    "Retrieve Walmart's supply chain cost data and export it as JSON structured data.",
    "Calculate Stripe's market penetration in cross-border payments and automatically generate a PowerPoint presentation.",
    "Retrieve Lululemon's market expansion data over the past 10 years and store it in the database for future querying.",
    "Analyze Apple's Vision Pro sales and automatically generate dynamic charts.",
    "Forecast Twitter's (X) ad growth over the next 2 years and generate an interactive data report.",
    "Calculate Tesla and BYD's growth in the global electric vehicle market and export the data in an Excel file."
]
